### ISSUE TITLE
Review Cart

### ISSUE THREAD

**Issue by Niniishere** [MatthewBeaulieu0/341-Website#10]
User sub-story:
As a customer, I should be able to click on the shopping cart, so that I can review it. I should also be able to see a display of my chosen items, the items' prices, the total taxes as well as the shipping fees so that I can have an overall report of the order. 
Story points: 5
Risk: medium risk, high value
Priority: High

- [x] Create a way for customers who have finalized their shopping list or who wish to see their cart item to be able to have an overall calculation of the fees
- [x] Use session variables in order to transfer the values between different pages
- [x] services (backend)
- [x] queries (backend)
- [x] routes (backend)
- [x] connect controller to services

Related epic: #3

**Comment by AnnaHsu1** [comment]
![image](https://user-images.githubusercontent.com/78278972/159057102-d87c2e2e-cfd6-4f88-b76c-434483504430.png)
