### ISSUE TITLE
Rating System

### ISSUE THREAD

**Issue by mihaicolaru** [MatthewBeaulieu0/341-Website#11]
Extra feature user story:
As a customer, I would like to view item ratings on the item page as well as leaving a rating for an item under the form of comment and mark out of 5 so site users have a better idea of the item quality.
Story points: 13
Risk: high risk, high value
Priority: low

- [x] star rating (up to 5 stars)
- [x] comment rating (text box)

Related epic #1

**Comment by Niniishere** [comment]
We have decided we would make the search bar our extra feature. This one will not be done.
