### ISSUE TITLE
Implementation of a buyer page

### ISSUE THREAD

**Issue by RandomKingRD** [MatthewBeaulieu0/341-Website#114]
User story:
As a user, I want to be able to see a list of my orders by pressing the "orders" button in the navigation bar so that I can keep track of my orders.

Story points: 5
Risk: Low risk, High value
Priority: Medium

- [x] Show orders of users
- [x] Show items of orders
- [x] Show quantity of items
- [x] Show image of items

[
![image](https://user-images.githubusercontent.com/65099738/162343221-debdd5b2-0841-4a74-89ef-68d8ee7a1a11.png)
](url)

**Comment by MohamadGSalim** [comment]
Buyer page is completed and works properly
