### ISSUE TITLE
Ability to track an order

### ISSUE THREAD

**Issue by dianaoana1** [MatthewBeaulieu0/341-Website#15]
User sub-story:
As a users, I should be able to view and track the orders I placed.

- [ ] Implement a randomly generated unique tracking number that the user has access to in order to view the status of their package as well as their shipping information.
- [ ] The tracking number should expire and become invalid once the order was delivered
- [ ] User should be able to view detailed information about their delivery progress, which includes the date, time, and progress status of their package.

related epic: #3

**Comment by mihaicolaru** [comment]
duplicate issue
