### ISSUE TITLE
Possibility to cancel an order

### ISSUE THREAD

**Issue by dianaoana1** [MatthewBeaulieu0/341-Website#16]
User-Story: A user who has placed an order should have the ability to cancel an order after it has been processed.

- [ ] Add a button labeled "Cancel your order" in the order information page that is clickable only if the package has not yet been shipped.
- [ ] If money has been withdrawn from the user's account, refund the user in accordance to the website's refund policy.

Related epic: #3

**Comment by mihaicolaru** [comment]
duplicate issue
