### ISSUE TITLE
Post items option (Seller)

### ISSUE THREAD

**Issue by mihaicolaru** [MatthewBeaulieu0/341-Website#19]
User Sub-story:
As a seller, I would like to be able to post items along with pertinent details (title, description, price, category) from my account to the site so potential customers could see and buy the items.
Story points: 5
Risk: medium risk, medium value
Priority: medium

- [x] new item option
- [x] item description fields
- [x] post item
- [x] add to database

Related epic: #6 
The acceptance testing for this one will be done during sprint 4 as it is not completed

**Comment by MatthewBeaulieu0** [comment]
This task will be done during spring 3 after the creation of seller/buyer accounts
