### ISSUE TITLE
Shopping cart

### ISSUE THREAD

**Issue by mihaicolaru** [MatthewBeaulieu0/341-Website#2]
Epic:
As a customers, I must have a shopping cart I can add items to while browsing items. The cart holds items that I add in it until checkout. I should be able to change the quantity of the items in the cart as well as remove them before the checkout process.
![image](https://user-images.githubusercontent.com/78886446/159058829-7bd471dd-e44e-4a76-bb97-daf2edf3ecda.png)

**Comment by RandomKingRD** [comment]
![Capture d’écran, le 2022-03-18 à 1 57 16 PM](https://user-images.githubusercontent.com/14958097/159057740-849e95fa-2a63-4696-bdac-5d2cb42e9362.png)
