### ISSUE TITLE
Cancel orders

### ISSUE THREAD

**Issue by mihaicolaru** [MatthewBeaulieu0/341-Website#20]
User Sub-story:
As a customer, I would like to be able to cancel an order that I have made on the website if I realize I do not need it or the shipping takes too long.
Story points: 5
Risk: low risk, medium value
Priority: Low

- [x] view orders placed in account
- [x] order schema
- [x] cancel order option
- [x] cancelation comment

Related epic: #6

**Comment by Niniishere** [comment]
We didn't process this feature since it is not required.
