### ISSUE TITLE
Create the main page

### ISSUE THREAD

**Issue by MatthewBeaulieu0** [MatthewBeaulieu0/341-Website#23]
Sub user-story:
As a customer, I would like to see a front page with a simple user interface (search, cart) when I enter the site so I can begin my browsing experience.
Story points: 8
Risk: high risk, high value
Priority: High

- [x] product get request 
- [x] display the main page
- [x] have a search bar
- [x] have a product selection
- [x] have a navigation bar
- [x] have a footer
- [x] have different product categories (could be under the navigation bar)
- [x] have a welcome page that leads to the main page

Related epic: #1

**Comment by Jonathan-Riso** [comment]
![image](https://user-images.githubusercontent.com/51491107/159057889-1b8b12e4-41fc-4b1d-9c19-2d0b72237aff.png)
