### ISSUE TITLE
Sprint 1 Completion

### ISSUE THREAD

**Issue by MatthewBeaulieu0** [MatthewBeaulieu0/341-Website#24]
- [x]  Create Repository, update project description, team members, readme
- [x] Description, objective, core features
- [x] Team meeting documentation
-  [x] High-level user stories for the 3 cores features
-  [x] Finish tasks before DDL (Thursday)
- [x] Meaningful commit description
-  [x] Commits referenced with issue number

**Comment by mihaicolaru** [comment]
milestone 1 completion confirmed
