### ISSUE TITLE
Checking out

### ISSUE THREAD

**Issue by mihaicolaru** [MatthewBeaulieu0/341-Website#3]
Epic:
As a customer, I should be able to check out the items in my shopping cart. I should also be able to enter my address, so that my order will be shipped to this particular address. I should be able to enter my payment details in order to complete my order. I should also have the option to specify if the billing address is the same as the shipping address and if it is not the case, I should be able to enter a new billing address. I must also be presented with different shipping options/methods, so that I can choose the one that is most convenient to me. I should be able to submit my order so that the checkout is complete. 

- [x] #52
- [x] Create forms to enter the necessary information about the payment fields as well as the shipping details
- [x] Customer data is saved and sent to database
![image](https://user-images.githubusercontent.com/78886446/159058619-fab3dfd0-c4ce-40d3-b97b-12fea0f457db.png)

**Comment by Jonathan-Riso** [comment]
![image](https://user-images.githubusercontent.com/51491107/159057520-eab6004e-593f-4d32-b840-88b0d3036e70.png)
