### ISSUE TITLE
Create Seller account

### ISSUE THREAD

**Issue by mihaicolaru** [MatthewBeaulieu0/341-Website#40]
User story:
As a product distributor, I would like to create a seller account to post items I sell to the site.
Story points: 3
Risk: low risk, medium value
Priority: medium

- [x] create account option
- [x] input fields

Related epic: #6 
![image](https://user-images.githubusercontent.com/78886446/159059130-efffe483-7e20-41fb-9f99-52b34f05690c.png)

**Comment by Jonathan-Riso** [comment]
![image](https://user-images.githubusercontent.com/51491107/159058219-70c46247-ee0c-40d5-821d-24c67438f4d1.png)
