### ISSUE TITLE
Click on products

### ISSUE THREAD

**Issue by Jonathan-Riso** [MatthewBeaulieu0/341-Website#5]
User sub-story:
(searched)
As a site user, I should be able to click on products to receive additional information about it which can include more pictures,  a description, how many are in stock, and any other information that may specifically concern the product.
Story points: 1
Risk: medium risk, high value
Priority: High

- [x] sketch out the page layout and plan out how the additional information will be layout.
- [x] implement the endpoint to query the additional information about the product if needed.
- [x] create the page in the front end based on the previous checkbox template.
- [x] Create tests to ensure nothing is broken and that the page functions and appears as intended.

Related epic: #1 
![image](https://user-images.githubusercontent.com/78886446/159056489-f4843362-51b7-4ded-bb3f-c0d65b5d9b06.png)

**Comment by mihaicolaru** [comment]
this has been completed
